<a href="https://colab.research.google.com/github/IbrahimMahidpur/ANN_Model/blob/main/BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.model_download("tensorflow/bert/tensorFlow2/bert-en-uncased-l-10-h-128-a-2")

print("Path to model files:", path)


  0%|          | 0.00/157k [00:00<?, ?B/s]



  0%|          | 0.00/226k [00:00<?, ?B/s]




  0%|          | 0.00/23.1M [00:00<?, ?B/s]



  0%|          | 0.00/7.70M [00:00<?, ?B/s]




100%|██████████| 3.05k/3.05k [00:00<00:00, 1.49MB/s]

100%|██████████| 157k/157k [00:00<00:00, 302kB/s]


100%|██████████| 226k/226k [00:00<00:00, 326kB/s]



  4%|▍         | 1.00M/23.1M [00:01<00:25, 902kB/s]



 13%|█▎        | 1.00M/7.70M [00:01<00:08, 827kB/s]


  9%|▊         | 2.00M/23.1M [00:01<00:12, 1.75MB/s]


 13%|█▎        | 3.00M/23.1M [00:01<00:07, 2.77MB/s]



 26%|██▌       | 2.00M/7.70M [00:01<00:03, 1.60MB/s]



 39%|███▉      | 3.00M/7.70M [00:01<00:01, 2.56MB/s]


 22%|██▏       | 5.00M/23.1M [00:01<00:03, 5.08MB/s]



 65%|██████▍   | 5.00M/7.70M [00:01<00:00, 4.71MB/s]


 35%|███▍      | 8.00M/23.1M [00:01<00:01, 8.67MB/s]



 91%|█████████ | 7.00M/7.70M [00:01<00:00, 7.19MB/s]


100%|██████████| 7.70M/7.70M [00:01<00:00, 4.22MB/s]



 52%|█████▏    | 12.0M/23.1M [00:01<00:00, 12.8MB/s]


 61%|██████    | 14.0M/23.1M [00:02<00:00, 14.5MB/s]


 69%|██████▉   | 16.0M/2

Path to model files: /root/.cache/kagglehub/models/tensorflow/bert/tensorFlow2/bert-en-uncased-l-10-h-128-a-2/2


In [23]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text # Import tensorflow_text to register the necessary ops
from keras import layers

preprocess_url='https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url= 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [24]:
bert_preprocess_model= hub.KerasLayer(preprocess_url)

In [25]:
text_test=['nice movie indeed','I love python programming']
text_preprocessed= bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [26]:
text_preprocessed['input_mask']

#first sentence is of 3 words but in mask there are 5 1's -> CLS word1 word2 word3 SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [27]:
bert_model=hub.KerasLayer(encoder_url)

In [28]:
bert_result=bert_model(text_preprocessed)  # word embeddings generation

In [29]:
bert_result.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [30]:
bert_result['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917741 , -0.21411921,  0.49769515, ...,  0.24465193,
        -0.47334474,  0.8175871 ],
       [-0.91712314, -0.47935188, -0.78656995, ..., -0.61751765,
        -0.7102687 ,  0.921843  ]], dtype=float32)>

In [31]:
bert_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292046,  0.08567815,  0.14476833, ..., -0.09677089,
          0.08722138,  0.07711098],
        [ 0.17839392, -0.19006105,  0.50349474, ..., -0.05869799,
          0.32717094, -0.15578488],
        [ 0.18701468, -0.43388787, -0.48875138, ..., -0.15502772,
          0.00145124, -0.24470966],
        ...,
        [ 0.12083106,  0.12884258,  0.46453524, ...,  0.07375515,
          0.17441994,  0.16522008],
        [ 0.07967864, -0.01190711,  0.50225407, ...,  0.13777758,
          0.21002217,  0.00624588],
        [-0.07212694, -0.2830348 ,  0.59033334, ...,  0.47551954,
          0.16668473, -0.08920345]],

       [[-0.07900596,  0.36335123, -0.2110157 , ..., -0.17183766,
          0.1629974 ,  0.6724269 ],
        [ 0.27883503,  0.43716323, -0.35764694, ..., -0.0446365 ,
          0.3831516 ,  0.5887988 ],
        [ 1.203767  ,  1.0727018 ,  0.4840876 , ...,  0.24920997,
          0.40730938,  0.404818  ],
        ...,