<a href="https://colab.research.google.com/github/IbrahimMahidpur/ANN_Model/blob/main/WordEmbeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow import keras
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews=['nice food',
         'amazing restaurant',
         'too good',
         'just loved it',
         'will go again',
         'horrible food',
         'never go there',
         'poor service',
         'poor quality',
         'needs improvement']
sentiments=np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
one_hot("amazing restaurant",30)

[25, 17]

In [6]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[29, 25], [25, 17], [1, 1], [22, 8, 18], [11, 17, 23], [26, 25], [27, 17, 17], [23, 21], [23, 2], [13, 8]]


In [8]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length,padding='post')
print(padded_reviews)

[[29 25  0]
 [25 17  0]
 [ 1  1  0]
 [22  8 18]
 [11 17 23]
 [26 25  0]
 [27 17 17]
 [23 21  0]
 [23  2  0]
 [13  8  0]]


In [13]:
embedded_vector_size=4
model=Sequential()

In [14]:
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
X= padded_reviews
y=sentiments

In [16]:
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.fit(X,y, epochs=50,verbose=0)

In [18]:
loss, accuracy =model.evaluate(X,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 416ms/step - accuracy: 1.0000 - loss: 0.6549


1.0

In [20]:
weights = model.get_layer('embedding').get_weights()[0]

In [21]:
len(weights)

30